
##Events
createEvent:
    path: /events
    controller: 'App\Infrastructure\Primary\Http\Controller\Event\CreateEventController'
    methods: [POST]

listEvent:
    path: /events
    controller: 'App\Infrastructure\Primary\Http\Controller\Event\listEventController'
    methods: [GET]

dispayCreateEventForm:
    path: /events/createFrom
    controller: 'App\Infrastructure\Primary\Http\Controller\Event\DisplayCreateEventFormController'
    methods: [GET]

## registration
createUserAndRegister:
    path: /events/{eventId}/register
    controller: 'App\Infrastructure\Primary\Http\Controller\Registration\RegisterAtEventController'
    methods: [POST]

listRegistrationByEvent:
    path: /events/{eventId}/registrations
    controller: 'App\Infrastructure\Primary\Http\Controller\Registration\listRegistrationByEventController'
    methods: [ GET ]
